version: '3.7'

services:
  wreck_app:
    image: 315tky/wreck:app_latest
    container_name: wreck_app
    deploy:
      resources:
        limits:
          memory: 1024m
    environment:
      - BASE64_ENCODE
      - REFRESH_TOKEN
      - POKILL_PROD_USERNAME
      - POKILL_PROD_PASSWORD
      - POKILL_PROD_DBNAME
      - POKILL_PROD_HOST
      - EVE_PROD_USERNAME
      - EVE_PROD_PASSWORD
      - EVE_PROD_DBNAME
      - EVE_PROD_HOST
      - USER_ID
      - GROUP_ID
      - USERNAME
      - USERGROUP
      - HOMEDIR
      - RAILS_ENV
    command: bash -c "rails db:migrate && bundle exec puma -C config/puma.rb"
    volumes:
      - ./tasks/eve_mysql_data_import:/app/wreck/lib/eve_mysql_data_import
      - /app/wreck/tmp/sockets:/app/wreck/tmp/sockets
    depends_on:
      - wreck_pg_db
      - wreck_mysql_db

  wreck_tasks:
    image: 315tky/wreck:tasks_latest
    container_name: wreck_tasks
    deploy:
      resources:
        limits: 
          memory: 128m
    depends_on:
      - wreck_app 
    command: crond -f -l 8 -L /app/wreck/log/cron.log
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/wreck/log:/app/wreck/log
      - ./tasks/cron_tasks/1min:/etc/periodic/hourly/:ro
      - ./tasks/cron_tasks/weekly:/etc/periodic/weekly/:ro
  wreck_pg_db:
    image: 315tky/wreck:postgres_latest
    container_name: wreck_postgres
    ports:
      - 5432
    deploy:
      resources:
        limits:
          memory: 256m
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - wreck_pg_data:/var/lib/postgresql/data

  wreck_mysql_db:
    image: 315tky/wreck:mysql_latest
    container_name: wreck_mysql
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - wreck_mysql_data:/var/lib/mysql

volumes:
  wreck_pg_data:
  wreck_mysql_data:
  wreck_tmp_data:
