FROM ruby:2.7.0

# set up user and group etc..
ARG USER_ID
ARG GROUP_ID
ARG USERNAME
ARG USERGROUP
ARG HOMEDIR

RUN groupadd --gid $GROUP_ID $USERNAME
RUN mkdir $HOMEDIR && useradd --uid $USER_ID --gid $GROUP_ID -d $HOMEDIR $USERNAME && chown -R $USERNAME:$USERGROUP $HOMEDIR

# install yarn repo
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# do an OS update and install required packages, and clean up
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client vim yarn nodejs \
    && rm -rf /var/lib/apt/lists/*

# set working dir
WORKDIR /app/wreck
RUN chown -R $USERNAME:$USERGROUP /app/wreck

# install bundler and gem files using bundler
COPY rails/Gemfile* ./
RUN gem install bundler:2.1.4 && bundle install

#USER $USER_ID
# Can maybe lose all the user and group stuff, especially in Prod.. need to test it without - nmd - 27th Feb 2020
