#!/bin/sh
## This file,  cron_tasks/15min/killmail_imports, is mounted on the cron docker container 
LOG="/app/wreck/log/cron.log"
_CONTAINER="wreck_app_dev"
echo "`date -Iseconds`: running rake task eve_import:all_eve_esi on $CONTAINER container" >> $LOG 2>&1 
docker exec $CONTAINER bin/rake eve_import:all_eve_esi >> $LOG 2>&1
echo "`date -Iseconds`: completed rake task eve_import:all_eve_esi on $CONTAINER container" >> $LOG 2>&1
