#!/bin/sh
## This file, cron_tasks/weekly/eve_mysql_imports, is mounted on the cron docker container 
LOG="/app/wreck/log/weekly_cron.log"
APP_CONTAINER="wreck_app"
DB_CONTAINER="wreck_mysql"

echo "`date -Iseconds`: running eve_mysql_sde_download to download and import any new sde" >> $LOG 2>&1
docker exec -i wreck_mysql /app/wreck/tasks/eve_mysql_data_import/mysql-drop-tables >> $LOG 2>&1
docker exec -i wreck_mysql /app/wreck/tasks/eve_mysql_data_import/eve_mysql_sde_download.sh >> $LOG 2>&1

echo "`date -Iseconds`: running rake eve_import:all_eve_mysql to pull data into postgres db" >> $LOG 2>&1
docker exec $APP_CONTAINER bin/rake eve_import:all_eve_mysql >> $LOG 2>&1

echo "`date -Iseconds`: completed tasks on  $APP_CONTAINER container" >> $LOG 2>&1

